/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Entidades.Compra;
import Entidades.DepositoMensual;
import Entidades.GastoMensual;
import Entidades.compraParaCombos;
import controladores.ControladorDepositosMensuales;
import controladores.ControladorGastosMensuales;
import controladores.controladorCompras;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utiles.Mes;

/**
 *
 * @author valkiria
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private ControladorDepositosMensuales controllerDepositos;
    private controladorCompras controllerCompras;
    private ControladorGastosMensuales controllerGastosMensuales;
    private DepositoMensual dp1;
        
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controllerCompras=new controladorCompras();       
        this.controllerDepositos=new ControladorDepositosMensuales();
        this.controllerGastosMensuales=new ControladorGastosMensuales();

        cargarMeses();
        cargarMesesGastos();
        cargarComprasGastosMensuales();

        botonBuscar.setEnabled(false);
        botonBuscar.setVisible(false);

    }
    
    public MenuPrincipal(DepositoMensual dp) {
        initComponents();
        this.controllerCompras=new controladorCompras();       
        this.controllerDepositos=new ControladorDepositosMensuales();
        this.controllerGastosMensuales=new ControladorGastosMensuales();

        cargarMeses();
        cargarMesesGastos();
        cargarComprasGastosMensuales();

        botonBuscar.setEnabled(false);
        botonBuscar.setVisible(false);
        
        mesesGastosMensuales.setSelectedItem(dp.getMes());
        anio.setYear(dp.getAnio());
        descripcion.setText(dp.getDescripcion());
        deposito.setText(""+dp.getDepositado());
        dp1=dp;
     
        List<Compra> comprasMesSelected=controllerCompras.buscarXMes(Mes.getMesXName(dp.getMes()));
        double saldoDepositos=0.0,saldoCompras=0.0;
        
        saldoDepositos=dp1.getDepositado();
        saldoCompras=comprasMesSelected.stream().mapToDouble(c->c.getPrecio()).sum();
        
        double saldoRestante=saldoDepositos-saldoCompras;
        
        saldoTotalMesDepositos.setText("SALDO TOTAL DEL MES HASTA LA FECHA: "+saldoDepositos);
        saldoRestanteMesDepositos.setText("SALDO RESTANTE DEL MES HASTA LA FECHA: "+saldoRestante);
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JTabbedPane();
        MenuDepositos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        anio = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox<>();
        deposito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        botonRegistrar = new javax.swing.JButton();
        botonLimpiarDepositos = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        saldoTotalMesDepositos = new javax.swing.JLabel();
        saldoRestanteMesDepositos = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        MenuGastosMensuales = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        nombreGastosMensuales = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        costoGastoMensual = new javax.swing.JTextField();
        labelVencimiento = new javax.swing.JLabel();
        fechaVencimientoGastoMensual = new com.toedter.calendar.JDateChooser();
        labelMes = new javax.swing.JLabel();
        labelPago = new javax.swing.JLabel();
        mesesGastosMensuales = new javax.swing.JComboBox<>();
        fechaPagadoGastoMensual = new com.toedter.calendar.JDateChooser();
        registrarGastoMensual = new javax.swing.JButton();
        limpiarDeGastoMensual = new javax.swing.JButton();
        liquidarGastosMensuales = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cuotasPagas = new javax.swing.JSpinner();
        cuotasTotales = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        comprasGastosMensuales = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        MenuCompras = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        lugarDeCompra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        precio1 = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MenuPrincipalFocusGained(evt);
            }
        });

        MenuDepositos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MenuDepositosFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("DEPOSITOS");

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel2.setText("AÑO:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("MES:");

        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        mes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mesPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setText("DEPOSITADO:");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel6.setText("DESCRIPCION:");

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonLimpiarDepositos.setText("LIMPIAR");
        botonLimpiarDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarDepositosActionPerformed(evt);
            }
        });

        botonConsultar.setText("CONSULTAR");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        saldoTotalMesDepositos.setText("SALDO TOTAL DEL MES HASTA LA FECHA: $");

        saldoRestanteMesDepositos.setText("SALDO RESTANTE DEL MES HASTA LA FECHA: $");

        jLabel17.setText("CUANDO SELECCIONE UN MES, SE MOSTRARA INFORMACION AQUI:");

        javax.swing.GroupLayout MenuDepositosLayout = new javax.swing.GroupLayout(MenuDepositos);
        MenuDepositos.setLayout(MenuDepositosLayout);
        MenuDepositosLayout.setHorizontalGroup(
            MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDepositosLayout.createSequentialGroup()
                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuDepositosLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDepositosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mes, 0, 184, Short.MAX_VALUE)
                                    .addComponent(anio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
            .addGroup(MenuDepositosLayout.createSequentialGroup()
                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(botonRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(botonLimpiarDepositos)
                        .addGap(54, 54, 54)
                        .addComponent(botonConsultar))
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saldoRestanteMesDepositos)
                            .addComponent(saldoTotalMesDepositos)))
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuDepositosLayout.setVerticalGroup(
            MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDepositosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(45, 45, 45)
                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuDepositosLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)))
                .addGap(65, 65, 65)
                .addGroup(MenuDepositosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar)
                    .addComponent(botonLimpiarDepositos)
                    .addComponent(botonConsultar))
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saldoTotalMesDepositos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoRestanteMesDepositos)
                .addContainerGap())
        );

        MenuPrincipal.addTab("DEPOSITOS", MenuDepositos);

        jLabel11.setText("GASTOS MENSUALES");

        jLabel12.setText("NOMBRE:");

        jLabel13.setText("COSTO:");

        labelVencimiento.setText("VENCIMIENTO:");

        labelMes.setText("MES PAGADO:");

        labelPago.setText("FECHA DE PAGADO:");

        mesesGastosMensuales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UN MES" }));
        mesesGastosMensuales.setPreferredSize(new java.awt.Dimension(188, 26));

        registrarGastoMensual.setText("REGISTRAR GASTO");
        registrarGastoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarGastoMensualActionPerformed(evt);
            }
        });

        limpiarDeGastoMensual.setText("LIMPIAR");
        limpiarDeGastoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarDeGastoMensualActionPerformed(evt);
            }
        });

        liquidarGastosMensuales.setText("LIQUIDAR GASTOS");

        jLabel14.setText("CUOTAS PAGAS:");

        jLabel16.setText("/ CUOTAS TOTALES:");

        jLabel15.setText("COMPRA VINCULADA:");

        MenuGastosMensuales.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(nombreGastosMensuales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(costoGastoMensual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(labelVencimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(fechaVencimientoGastoMensual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(labelMes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(labelPago, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(mesesGastosMensuales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(fechaPagadoGastoMensual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(registrarGastoMensual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(limpiarDeGastoMensual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(liquidarGastosMensuales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(cuotasPagas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(cuotasTotales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(comprasGastosMensuales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuGastosMensuales.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuGastosMensualesLayout = new javax.swing.GroupLayout(MenuGastosMensuales);
        MenuGastosMensuales.setLayout(MenuGastosMensualesLayout);
        MenuGastosMensualesLayout.setHorizontalGroup(
            MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                        .addComponent(nombreGastosMensuales)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(costoGastoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuGastosMensualesLayout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(labelMes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesesGastosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42))
                                .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                                    .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuGastosMensualesLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(labelVencimiento))
                                        .addComponent(labelPago))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fechaVencimientoGastoMensual, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addComponent(fechaPagadoGastoMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                                .addComponent(cuotasPagas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuotasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comprasGastosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuGastosMensualesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registrarGastoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(limpiarDeGastoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(liquidarGastosMensuales)
                .addGap(119, 119, 119))
        );
        MenuGastosMensualesLayout.setVerticalGroup(
            MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuGastosMensualesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addGap(42, 42, 42)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreGastosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(23, 23, 23)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(costoGastoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMes)
                    .addComponent(mesesGastosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVencimiento)
                    .addComponent(fechaVencimientoGastoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaPagadoGastoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPago))
                .addGap(23, 23, 23)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cuotasPagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(cuotasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprasGastosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42)
                .addGroup(MenuGastosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarGastoMensual)
                    .addComponent(limpiarDeGastoMensual)
                    .addComponent(liquidarGastosMensuales))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        MenuPrincipal.addTab("GASTOS MENSUALES", MenuGastosMensuales);

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel5.setText("CONTABILIDAD CASERA");

        descripcion1.setColumns(20);
        descripcion1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripcion1.setRows(5);
        jScrollPane2.setViewportView(descripcion1);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel7.setText("DESCRIPCION DE COMPRA:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel8.setText("FECHA DE COMPRA:");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel9.setText("LUGAR DE COMPRA:");

        lugarDeCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel10.setText("PRECIO TOTAL:");

        precio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonBuscar.setText("BUSCAR COMPRAS");

        MenuCompras.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(lugarDeCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(precio1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(botonGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(botonLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuCompras.setLayer(botonBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuComprasLayout = new javax.swing.GroupLayout(MenuCompras);
        MenuCompras.setLayout(MenuComprasLayout);
        MenuComprasLayout.setHorizontalGroup(
            MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuComprasLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuComprasLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuComprasLayout.createSequentialGroup()
                        .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuComprasLayout.createSequentialGroup()
                                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47))
                            .addGroup(MenuComprasLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(44, 44, 44)))
                        .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lugarDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuComprasLayout.createSequentialGroup()
                        .addComponent(botonGuardar)
                        .addGap(66, 66, 66)
                        .addComponent(botonLimpiar)
                        .addGap(62, 62, 62)
                        .addComponent(botonBuscar)
                        .addGap(106, 106, 106))))
        );
        MenuComprasLayout.setVerticalGroup(
            MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuComprasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuComprasLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7)
                        .addGap(69, 69, 69))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lugarDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(51, 51, 51)
                .addGroup(MenuComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonLimpiar)
                    .addComponent(botonBuscar))
                .addContainerGap())
        );

        MenuPrincipal.addTab("COMPRAS", MenuCompras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        try{
            int anio1=anio.getValue();
            if(mes.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Asegurese de seleccionar un mes");
                return;
            }
            String mes1=mes.getSelectedItem().toString();

            double deposito1=Double.parseDouble(deposito.getText());

            String descrip=descripcion.getText();
            controllerDepositos.guardar(new DepositoMensual(anio1, Mes.getMesXName(mes1), deposito1,descrip));

            JOptionPane.showMessageDialog(null, "Deposito registrado con exito");

            botonLimpiarDepositosActionPerformed(evt);

        }catch(NumberFormatException ex){
            if(ex.getMessage().equalsIgnoreCase("empty String")){
                JOptionPane.showMessageDialog(null, "asegurese de ingresar un valor en"
                    + " el campo deposito");
            }else if(ex.getMessage().startsWith("For input string")){
                JOptionPane.showMessageDialog(null, "asegurese de ingresar solo numeros en el campo "
                    + "deposito, y para separar centavos use solo un punto, error: "+ex.getMessage());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "hubo un error al guardar el deposito, error: "+e.getMessage());
        }

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonLimpiarDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarDepositosActionPerformed
        deposito.setText("");
        mes.setSelectedIndex(0);
        anio.setValue(LocalDate.now().getYear());
        descripcion.setText("");
    }//GEN-LAST:event_botonLimpiarDepositosActionPerformed

    private void MenuPrincipalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MenuPrincipalFocusGained


    }//GEN-LAST:event_MenuPrincipalFocusGained

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Compra compra=new Compra(descripcion1.getText(), fecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), lugarDeCompra.getText(), Double.parseDouble(precio1.getText()));
        try{
            controllerCompras.guardar(compra);
            JOptionPane.showMessageDialog(null, "Compra registrada efectivamente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ocurrio un error: "+e.getMessage());
        }
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        descripcion1.setText("");
        precio1.setText("");
        fecha.setDate(null);
        lugarDeCompra.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void MenuDepositosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MenuDepositosFocusGained
        
    }//GEN-LAST:event_MenuDepositosFocusGained

    private void registrarGastoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarGastoMensualActionPerformed
        String nombreGasto=nombreGastosMensuales.getText();
        double costo=Double.parseDouble(costoGastoMensual.getText());
        LocalDate vencimiento=fechaVencimientoGastoMensual.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Mes mesPagado=Mes.getMesXName(mesesGastosMensuales.getSelectedItem().toString());
        LocalDate fechaPago1=fechaPagadoGastoMensual.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int cuotasPagas = (int) this.cuotasPagas.getValue();
        int cuotasTotales=(int)this.cuotasTotales.getValue();
        compraParaCombos compraItem=(compraParaCombos)comprasGastosMensuales.getSelectedItem();
        long idCompra=compraItem.getId();
        Compra compra= controllerCompras.buscarXID(idCompra);
        controllerGastosMensuales.guardar(new GastoMensual(nombreGasto, costo, mesPagado, vencimiento ,  fechaPago1,cuotasTotales,cuotasPagas,compra));
        
    }//GEN-LAST:event_registrarGastoMensualActionPerformed

    private void limpiarDeGastoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarDeGastoMensualActionPerformed
        nombreGastosMensuales.setText("");
        costoGastoMensual.setText("");
        fechaVencimientoGastoMensual.setDate(null);
        mesesGastosMensuales.setSelectedIndex(0);
        fechaPagadoGastoMensual.cleanup();
        
    }//GEN-LAST:event_limpiarDeGastoMensualActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        consultarSaldos cs=new consultarSaldos();
        cs.setVisible(true);
        cs.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void mesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mesPropertyChange
        
        
    }//GEN-LAST:event_mesPropertyChange

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        calcularSaldoHastaLaFecha();
    }//GEN-LAST:event_mesActionPerformed
     public void calcularSaldoHastaLaFecha(){
        try{
        Mes mesSelected=Mes.getMesXName(mes.getSelectedItem().toString());
        ArrayList<DepositoMensual> depositosHastaMesSelected=controllerDepositos.buscarDepositosXMes(mesSelected.obtenerStringMes());
        List<Compra> comprasMesSelected=controllerCompras.buscarXMes(mesSelected);
        double saldoDepositos=0.0,saldoCompras=0.0;
        if(depositosHastaMesSelected.size()>1){
            int o=JOptionPane.showConfirmDialog(null, "Se encontraron mas de un deposito en el mismo mes, desea sumarlos?");
            if(o==0){
                 saldoDepositos=depositosHastaMesSelected.stream().mapToDouble(c->c.getDepositado()).sum();
                 saldoCompras=comprasMesSelected.stream().mapToDouble(c->c.getPrecio()).sum();
        
                double saldoRestante=saldoDepositos-saldoCompras;
        
            }else{
               seleccionarSaldo s1= new seleccionarSaldo(depositosHastaMesSelected);
               s1.setVisible(true);
               this.dispose();
               
               
            }
        } 
        double saldoRestante=saldoDepositos-saldoCompras;
        
        saldoTotalMesDepositos.setText("SALDO TOTAL DEL MES HASTA LA FECHA: "+saldoDepositos);
        saldoRestanteMesDepositos.setText("SALDO RESTANTE DEL MES HASTA LA FECHA: "+saldoRestante);
        }catch(Exception e){
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MenuCompras;
    private javax.swing.JPanel MenuDepositos;
    private javax.swing.JDesktopPane MenuGastosMensuales;
    private javax.swing.JTabbedPane MenuPrincipal;
    private com.toedter.calendar.JYearChooser anio;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonLimpiarDepositos;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JComboBox<compraParaCombos> comprasGastosMensuales;
    private javax.swing.JTextField costoGastoMensual;
    private javax.swing.JSpinner cuotasPagas;
    private javax.swing.JSpinner cuotasTotales;
    private javax.swing.JTextField deposito;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextArea descripcion1;
    private com.toedter.calendar.JDateChooser fecha;
    private com.toedter.calendar.JDateChooser fechaPagadoGastoMensual;
    private com.toedter.calendar.JDateChooser fechaVencimientoGastoMensual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelPago;
    private javax.swing.JLabel labelVencimiento;
    private javax.swing.JButton limpiarDeGastoMensual;
    private javax.swing.JButton liquidarGastosMensuales;
    private javax.swing.JTextField lugarDeCompra;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JComboBox<String> mesesGastosMensuales;
    private javax.swing.JTextField nombreGastosMensuales;
    private javax.swing.JTextField precio1;
    private javax.swing.JButton registrarGastoMensual;
    private javax.swing.JLabel saldoRestanteMesDepositos;
    private javax.swing.JLabel saldoTotalMesDepositos;
    // End of variables declaration//GEN-END:variables

    public void cargarMeses(){
        mes.addItem("SELECCIONA UN MES");
        for (int i = 1; i < 13; i++) {
            mes.addItem(Mes.getMesXid(i).obtenerStringMes());
        }
    }
    public void cargarMesesGastos(){
        for (int i = 1; i < 13; i++) {
            mesesGastosMensuales.addItem(Mes.getMesXid(i).obtenerStringMes());
        }
    }
    public void cargarComprasGastosMensuales(){

        controllerCompras.buscarTodos()
                .iterator()
                .forEachRemaining(
                        comp->{
                            comprasGastosMensuales.addItem(new compraParaCombos(comp.getIdCompra(), comp.getDescripcion()));
                        }
                        );

    }
 
}
